spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_management_system
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.gym.pojo


rag:
  api:
    url: "http://localhost:9000"


server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
